### ISSUE TITLE
Add subregion special cases and custom combinations

### ISSUE THREAD

**Issue by daviskirk** [daviskirk/german-holidays#9]
1. Possibly we need a way of specifying subregions of states, for the parts of Bavaria where Mariä Himmelfahrt is not a holiday and also for "Augsburger hohes Friedensfest"
2. In order to facilitate this we could add an option for specifying a list of included/excluded holidays (by name) which would modify the base list generated from the state code provided

**Comment by karimbk** [comment]
thanks for this useful tool! I have two questions though: 
1) Can I compare a timestamp against the 'german-holidays' list? Lets say I have a pandas timestamp column, and I want to compare each row against the 'german-holidays', and set a 'True' flag on a new column if it's one?
2) Is there a possibility to compare against german-holidays NATIONWIDE, and not by state? Because I've see that you're calling the holidays with the state_id, let's say 'NW'.. But I need to compare if the holiday is a nationwide holiday.

**Comment by daviskirk** [comment]
@karimbk sorry for the late answer.  I'm sure you've found other solutions but I'll answer here anyway:

1. There isn't any builtin way to do this, but you can compare them manually:

```python
index = pd.date_range('2014', '2015')
cls = german_holidays.get_german_holiday_calendar('NW')
holidays = cls().holidays(index[0], index[-1])

index.isin(holidays)
```

gives you the output

```
array([ True, False, False, False, False, False, False, False, False,
       ...
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True])
```

2. No this is not possible directly.  You will also need to decide what this means.  Does notionwide mean that ALL states have this holiday or that any state has a holiday?

```python
from german_holidays import get_german_holiday_calendar 
states = ['BW', 'BY', 'BE', 'BB', 'HB', 'HH', 'HE', 'MV', 'NI', 'NW', 'RP', 'SL', 'SN', 'ST', 'SH', 'TH']
start, end = '2014', '2015'
all_of_germany_has_a_holiday = pd.concat([
    get_german_holiday_calendar(state)().holidays(start, end).to_series()
    for state in states
], axis=1).dropna().index
```

As a final note:  I updated the README to say this as weill but: This library was born before there were better solutions that now exist. The library [holidays](https://github.com/dr-prodigy/python-holidays) is better maintained and more accurate and includes not only german holidays but many other countries as well. I would suggest you use it instead.
